// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChoOx-FSHfBgdDGdjcGLLdRLDOqkL1Bgk',
    appId: '1:1071368477024:web:40ecc4ac054dbee2342605',
    messagingSenderId: '1071368477024',
    projectId: 'individual-assignment-27ee4',
    authDomain: 'individual-assignment-27ee4.firebaseapp.com',
    storageBucket: 'individual-assignment-27ee4.appspot.com',
    measurementId: 'G-F521BTBHPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3J6ObPX39DYzNseai8Qwai513hXLYTCE',
    appId: '1:1071368477024:android:98e43d90cbe9f6b7342605',
    messagingSenderId: '1071368477024',
    projectId: 'individual-assignment-27ee4',
    storageBucket: 'individual-assignment-27ee4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyLykZl376JV4k0gt8IhFoAaaL-zPi_YY',
    appId: '1:1071368477024:ios:8d6592af4ac13965342605',
    messagingSenderId: '1071368477024',
    projectId: 'individual-assignment-27ee4',
    storageBucket: 'individual-assignment-27ee4.appspot.com',
    iosClientId: '1071368477024-9au38r4jaslomqfcmb3070sj333b4jsf.apps.googleusercontent.com',
    iosBundleId: 'com.example.nBaz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyLykZl376JV4k0gt8IhFoAaaL-zPi_YY',
    appId: '1:1071368477024:ios:8d6592af4ac13965342605',
    messagingSenderId: '1071368477024',
    projectId: 'individual-assignment-27ee4',
    storageBucket: 'individual-assignment-27ee4.appspot.com',
    iosClientId: '1071368477024-9au38r4jaslomqfcmb3070sj333b4jsf.apps.googleusercontent.com',
    iosBundleId: 'com.example.nBaz',
  );
}
